### ISSUE TITLE
'Settings' object has no attribute 'ABS_PATH'

### ISSUE THREAD

**Issue by capt4ce** [XI-lab/axel#1]
Hi, firstly I would like to thank you for open sourcing this kind of project. Lately I have been assigned to a exploratory project and I had no clue n references, and you act as my hero!

When I was trying to run the project with 'python manage.py', an error accurs:

> Traceback (most recent call last):
>   File "manage.py", line 24, in <module>
>     build_index()
>   File "/projects/examples/axel/axel/articles/utils/concepts_index.py", line 34, in build_index
>     from axel.stats.models import Collocations
>   File "/projects/examples/axel/axel/stats/models.py", line 12, in <module>
>     import axel.stats.scores as scores
>   File "/projects/examples/axel/axel/stats/scores/__init__.py", line 15, in <module>
>     ontology = set(codecs.open(settings.ABS_PATH('ontology.csv'), 'r', 'utf-8').read().split('\n'))
>   File "/home/capt4ce/.local/lib/python2.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
>     val = getattr(self._wrapped, name)
> AttributeError: 'Settings' object has no attribute 'ABS_PATH'

I hope you can provide a solution ASAP, as I have to start the project.
Thanks!

**Comment by dragoon** [comment]
Hello, thanks for the appreciation of the project. However, I haven't been working on it for a few years. I have developed it for the django version 1.6, and the properties might have changed in newer versions. If you want to get it working, I suggest you try to downgrade to Django 1.6, otherwise feel free to make a pull request that makes the project work with newer versions.

**Comment by capt4ce** [comment]
Thanks for your response.
I have been working on trying to make the project run on my machine for days, everything I have tried from downgrading the Django till making disabling some part of the code that I assume producing problems but it took me nowhere.
So, instead of trying to make your project work on my machine, would you provide me some references (articles, tutorials, videos, theories, or your project design etc) so that I can create an exploratory search project? I have been trying to find references but got nothing except your project.
Thanks!

**Comment by dragoon** [comment]
I did my project as a part of a larger effort for scientist to discover relevant paper, maybe you can draw the inspiration from there: http://sciencewise.info/
